project:
  type: website
  output-dir: "docs"
  title: "Michael Lopez"
format:
  html:
    theme: www/web_report.scss
    toc-title: Contents
    toc: false
    toc-depth: 2
    toc-location: right
    anchor-sections: false
    code-summary: "Reveal Code"
    code-copy: hover
    code-fold: true
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 850px
      margin-width: 300px
    code-block-bg: true
    code-block-border-left: "#008097"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    warning: FALSE
    error: TRUE
    echo: FALSE
    message: FALSE
website:
  search: FALSE
#    location: navbar
#    type: textbox
#  favicon: www/images/CPAL_favicon.ico
  navbar:
      pinned: TRUE
      search: FALSE
#      logo: www/images/logo-square.png
#      logo-href: "https://childpovertyactionlab.github.io/cpaldirectory/"
      collapse: FALSE
      right:
        - icon: house-door-fill
          text: "Home"
          href: index.html
        - icon: card-list
          text: "Resume"
          href: resume.html
        - icon: github
          text: "Github"
          href: "https://github.com/lopezmichael/"
  page-footer:
    background: "#1e1e1e"
