---
title: 'Projects'
output:
  distill::distill_article:
    toc:false:
      theme: theme.css
#favicon: "images/favicon.ico"
github-repo: lopezmichael/portfolio
---

**This site is currently under construction.**

## Reports

**[Afterschool Landscape Tool](https://childpovertyactionlab.github.io/dallas-afterschool/)**

This is an external report/analysis generated for an organization known as Dallas Afterschool intended to help them identify neighborhoods where there may be a need for additional afterschool programming based on some specified criteria. This website and analysis/report was generated through R, Distil, Rmarkdown, and QGIS. There was some additional support from Dallas Afterschool on scope and language, but otherwise I was the project lead.

**[Dallas Police Department Incident Report](https://childpovertyactionlab.github.io/dpd-incident-report//)**

This is an internal report/analysis generated through a combination of R, Distil, and Rmarkdown. Its intention is to visualize crime trends in the City of Dallas.

## Web Tools

**[North Texas Evictions Project](https://northtexasevictions.org/)**

This is an external tool that is generated using eviction case filings that we have obtained access to from a number of North Texas Counties. This tool is used by a number of organizations across North Texas that work in housing stability to identify where to direct resources based on current eviction filing trends.
The website/back-end was created with by an external developer, but all analysis/coding and weekly updates are done by myself.

**[Community Resource Explorer](https://dallasisd.resourceexplorer.org/)**

This is an external tool that was generated to help identify resource access surrounding Dallas Independent School District campuses across a number of various metrics. 
The website/back-end was created with an external developer, but all analysis/coding was done by myself. 
If you click the 'Go to the Explorer' section it will take you directly to the tool.

**[North Texas Social Mobility Hub](https://socialmobilityhub.org/)**

In collaboration with the University of North Texas at Dallas this tool is focused on the ways that knowledge about barriers and drivers towards upward mobility can be put into action, and how the chances for upward mobility can be increased for all communities.
The website/back-end was created with an external developer, but all analysis/coding was done by myself. 
If you click the 'Go to Data Explorer' section it will take you directly to the tool.
